---
title: "Portfolio"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## 목차

1. [Simulate Vasicek r(t)]
2. [Pricing Barrier option]
3. [Ameshousing]

***

## Simulate Vasicek r(t)

```{r}
## Simulate Vasicek r(t)
set.seed(3)

# parameter 설정
r0 <- 0.03
a <- 0.2
b <- 0.03
sigma <- 0.01
n <- 10    # trials
T <- 10    # (10년만기 국고채)
h <- 3600    # subintervals
dt <- T/h   


# 시나리오 행렬 생성
v_m <- as.data.frame(matrix(data=0, ncol = 21, nrow = h+1)) 
v_m[1,1:10] <- r0
colnames(v_m)=c("scenario1","scenario2","scenario3","scenario4","scenario5",
                "scenario6","scenario7","scenario8","scenario9","scenario10", 
                "price1", "price2", "price3", "price4", "price5",
                "price6", "price7", "price8", "price9", "price10","t")

for(j in 1:n){
  for(i in 2:(h+1)){
    dr <- a*(b-v_m[i-1,j])*dt + sigma*sqrt(dt)*rnorm(1,0,1)   # dr = a(b-r)dt + sigma*dz, where dz~N(0,dt) > using normal approximation
    v_m[i,j] <- v_m[i-1,j] + dr   # r(t)
  }
} 

v_m[,21] <- seq(0, 3600)
v_m[,21] <- v_m[,21]/3600


# plot r(t)
t <- seq(0, T, dt)
matplot(t, v_m[,1:10], type="l", lty=3, col = 1:10, main="Short-Rate Paths", ylab="r(t)") 



# pricing bond
Bondprice <- function(rt, a, b, sigma, k){
    rbar <- b-(0.5*sigma^2/a^2)  # k= T-t
    b.t <- (1/a)*(1-exp(-k*a))   # B(t,T) 
    a.t <- exp(rbar*(b.t-k)-(b.t^2*sigma^2/(4*a)))   # A(t,T)
    return(a.t*exp(-b.t*rt))
  }

for (i in 1:h+1){
  for (j in 1:n){
    v_m[i,j+10] <- Bondprice(v_m[i,j], a, b, sigma, v_m[i,21])  
  }
  
}

v_mp <- v_m[-1,]

matplot(seq(1/3600,T,dt), v_mp[,11:20], type="l", lty=1, col = 1:10, main="Bond price", ylab="P(t,T)", xlab = "maturity")

```
***

## Pricing Barrier option

```{r}
# Assumptions

scenario <- 100
interval <- 600
t <- 1/(interval)
r <- 0.03
sigma <-0.4
mu <- r-0.5*sigma^2

s0 <- 100
k <- 110
barrier <- 120
set.seed(123)


# Z

z <- as.data.frame(matrix(rnorm(scenario*interval), nrow=scenario, ncol=interval))

xx <- as.data.frame(matrix(data=0, nrow=scenario, ncol=interval+1))

for (i in 1:scenario){
  for(j in 1:interval){
    xx[i,j+1] <- xx[i,j] + (mu*t+(sigma*sqrt(t)*z[i,j]))
  }
}


plot(x=seq(1, 600, 1),y=s0*exp(xx[3,2:601]), main = "X(T)", type = "l", ylab="X(t)", xlab="interval")


## Payoff 식 만들어야함

result <- matrix(NA, scenario, 1)

for(i in 1:scenario){
  result[i,1]<- exp(-r*1)*(s0*exp(xx[i,601])-k)  
}


mean(result[1:scenario,1])
```
***


## Ameshousing

```{r}
library(ggplot2)
library(AmesHousing)
library(tidyverse)
library(caret)
library(GGally)
library(treemap)
library(ggridges)

house <- ames_raw

# Continuous variables
## SalePrice graph

### divde data into 30 equal bins or intervals.

ggplot(house, aes(SalePrice)) + geom_histogram()
boxplot(house$SalePrice, main = "SalePrice")

### width : 5000, count the number of data

house %>%
  count(cut_width(SalePrice, width = 5000)) %>%
  arrange(desc(n))

### log transformed histogram

ggplot(house, aes(SalePrice)) +
  geom_histogram(bins = 50) +
  scale_x_log10(
    labels = scales::dollar,
    breaks = c(50000, 150000, 250000, 350000)
  )

### look at normality by using Q-Q plot

### raw data

qqnorm(house$SalePrice, main = "raw data Q-Q plot")
qqline(house$SalePrice)

### log data

qqnorm(log(house$SalePrice), main = "log data Q-Q plot")
qqline(log(house$SalePrice))

### plot

plot(house$SalePrice, col = rgb(0.5, 0, 0.5, alpha = 0.3), ylab = "SalePrice")


## Total square feet of basement area

### graph `Total Bsmt SF`

ggplot(house, aes(`Total Bsmt SF`)) + geom_histogram()
boxplot(house$`Total Bsmt SF`, main = "Total Bsmt SF", na.rm = TRUE)




# Bar charts : One of the most commonly used data visualizations for categorical variables
# MS_Zoning
ggplot(house, aes(`MS Zoning`)) + geom_bar()

# total count
p1 <- house %>%
  count(`MS Zoning`) %>%
  ggplot(aes(reorder(`MS Zoning`, n), n)) + geom_col() + coord_flip() + ggtitle("Total count")

# percent of whole
p2 <- house %>%
  count(`MS Zoning`) %>%
  mutate(pct = n / sum(n)) %>%
  ggplot(aes(reorder(`MS Zoning`, pct), pct)) + geom_col() + coord_flip() + ggtitle("Percent of whole")

gridExtra::grid.arrange(p1, p2, nrow =1)

# n
house %>%
  count(`MS Zoning`) %>%
  mutate(pct = n / sum(n)) %>%
  arrange(pct)  # This imbalanced nature can cause problems in future analytic models.
                # So it may make sense to combine these infrequent levels into an "other" category.


# make "other" category to MS Zoning
house %>%
  mutate(`MS Zoning` = fct_lump(`MS Zoning`, n = 2)) %>%  # 주요 인자 n개만 나타내고 나머지는 other 처리
  count(`MS Zoning`) %>%
  mutate(pct = n / sum(n)) %>%
  ggplot(aes(reorder(`MS Zoning`, pct), pct)) + geom_col() + coord_flip()

house %>%
  mutate(Neighborhood = fct_lump(Neighborhood, n = 26)) %>%
  count(Neighborhood) %>%
  mutate(pct = n / sum(n)) %>%
  ggplot(aes(pct, reorder(Neighborhood, pct))) + geom_point() +
  geom_segment(aes(x = 0, xend = pct, y = Neighborhood, yend = Neighborhood), size = 0.3)

# order variable (kitchenQual)
house %>%
  mutate(`Kitchen Qual` = fct_relevel(`Kitchen Qual`, "Po", "Fa", "TA", "Gd")) %>%
  ggplot(aes(`Kitchen Qual`)) + geom_bar()


# categorial variable that has set intervals and may even be identified by integer values.
p <-  ggplot(house, aes(factor(`Mo Sold`))) + geom_bar()
p <- p + labs(x = "sold month", y = "frequency")
p


# Year Built
ggplot(house, aes(`Year Built`)) + geom_histogram()

house %>%
  count(cut_width(`Year Built`, width = 10)) %>%  # interval : 10-year
  arrange(desc(n))

ggplot(house, aes(`Year Built`)) +
  geom_histogram(breaks = seq(1865, 2005, by = 5)) + 
  geom_vline(xintercept = c(1980, 1990), col = "red", lty = "dashed")


# One of the most popular plots to assess association is the scatter plot.
# `Gr Liv Area` & SalePrice
ggplot(house, aes(x = `Gr Liv Area`, y = SalePrice)) + geom_point(alpha = .3)

p1 <- ggplot(house, aes(x = `Gr Liv Area`, y = SalePrice)) + geom_point(alpha = 0.3) +
  geom_smooth(method = "lm", se = TRUE, color = "red", lty = "dashed") + 
  geom_smooth(se = TRUE, lty = "dashed") + ggtitle("raw data variables") +
  geom_text(x=4500, y=500000, label="y=111.694x+13289.634") + 
  geom_text(x=4500, y=450000, label="R²=0.4995")
p1

p2 <- ggplot(house, aes(x = `Gr Liv Area`, y = SalePrice)) + geom_point(alpha = 0.3) +
  geom_smooth(method = "lm", se = TRUE, color = "red", lty = "dashed") + 
  geom_smooth(se = TRUE, lty = "dashed") + 
  scale_x_log10() + scale_y_log10() + ggtitle("log data variables") +
  geom_text(x=1000, y=30000, label="y=0.90781x+2.35830") + 
  geom_text(x=3000, y=30000, label="R²=0.523") 
p2

gridExtra::grid.arrange(p1, p2, ncol = 2)

# `Total Bsmt SF` & SalePrice

p1 <- ggplot(house, aes(x = `Total Bsmt SF`, y = SalePrice)) + geom_point(alpha = 0.3) +
  geom_smooth(method = "lm", se = TRUE, color = "red", lty = "dashed") + 
  geom_smooth(se = TRUE, lty = "dashed") + ggtitle("raw data variables")
p1

p2 <- ggplot(house, aes(x = `Total Bsmt SF`, y = SalePrice)) + geom_point(alpha = 0.3) +
  geom_smooth(method = "lm", se = TRUE, color = "red", lty = "dashed") + 
  geom_smooth(se = TRUE, lty = "dashed") + 
  scale_x_log10() + scale_y_log10() + ggtitle("log data variables")
p2

gridExtra::grid.arrange(p1, p2, ncol = 2)


# `Misc Val` & SalePrice > no correlation?
p1 <- ggplot(house, aes(x = `Misc Val`, y = SalePrice)) + geom_point(alpha = 0.3) +
  geom_smooth(method = "lm", se = TRUE, color = "red", lty = "dashed") + 
  geom_smooth(se = TRUE, lty = "dashed") + ggtitle("raw data variables")
p1

p2 <- ggplot(house, aes(x = `Misc Val`, y = SalePrice)) + geom_point(alpha = 0.3) +
  geom_smooth(method = "lm", se = TRUE, color = "red", lty = "dashed") + 
  geom_smooth(se = TRUE, lty = "dashed") + 
  scale_x_log10() + scale_y_log10() + ggtitle("log data variables")
p2

gridExtra::grid.arrange(p1, p2, ncol = 2)


# `Year Built` & SalePrice
plot(house$`Year Built`, house$SalePrice)

p1 <- ggplot(house, aes(x = `Year Built`, y = SalePrice)) + geom_point(alpha = 0.3) +
  geom_smooth(method = "lm", se = TRUE, color = "red", lty = "dashed") + 
  geom_smooth(se = TRUE, lty = "dashed") + ggtitle("raw data variables")
p1

p2 <- ggplot(house, aes(x = `Year Built`, y = SalePrice)) + geom_point(alpha = 0.3) +
  geom_smooth(method = "lm", se = TRUE, color = "red", lty = "dashed") + 
  geom_smooth(se = TRUE, lty = "dashed") + 
  scale_x_log10() + scale_y_log10() + ggtitle("log data variables")
p2

gridExtra::grid.arrange(p1, p2, ncol = 2)


# `Pool Area` & SalePrice

p1 <- ggplot(house, aes(x = `Pool Area`, y = SalePrice)) + geom_point(alpha = 0.3) +
  geom_smooth(method = "lm", se = TRUE, color = "red", lty = "dashed") + 
  geom_smooth(se = TRUE, lty = "dashed") + ggtitle("raw data variables")
p1

p2 <- ggplot(house, aes(x = `Pool Area`, y = SalePrice)) + geom_point(alpha = 0.3) +
  geom_smooth(method = "lm", se = TRUE, color = "red", lty = "dashed") + 
  geom_smooth(se = TRUE, lty = "dashed") + 
  scale_x_log10() + scale_y_log10() + ggtitle("log data variables")
p2

gridExtra::grid.arrange(p1, p2, ncol = 2)

# `MS Zoning` & SalePrice
x1 <- ggplot(house, aes(x = factor(`Bedroom AbvGr`), y = SalePrice)) +
  geom_jitter(alpha = .2, width = .1)
x1


# `Lot Shape` & SalePrice
x2 <- ggplot(house, aes(x = factor(`Lot Shape`), y = SalePrice)) +
  geom_jitter(alpha = .2, width = .1)
x2


# `Land Contour` & SalePrice
x3 <- ggplot(house, aes(x = factor(`Land Contour`), y = SalePrice)) +
  geom_jitter(alpha = .2, width = .1)
x3


ggplot(house, aes(x = SalePrice, y = `Neighborhood`)) + 
  ggridges::geom_density_ridges() +
  scale_x_continuous(labels = scales::dollar)

```
***

